[COCA-258]  Ajuste componete tabs
Adapcon/vue-polar-bear pull request #119
Opened 2022-05-04 07:19 UTC by mickaelnn

### Description
This PR fixes the layout for pbtabs, all this changes was validated with @brunaboeger,
 the list of changes was described on jira card. 
 
 ### Jira
 [COCA-258 - Ajuste componete tabs](https://adapcon.atlassian.net/browse/COCA-258)
 
 ### Screenshots
![image](https://user-images.githubusercontent.com/62998447/166636949-44720f92-bf4b-4ea2-aeb4-6122c98bc709.png)
![image](https://user-images.githubusercontent.com/62998447/166637457-23d5cba0-9c85-4e32-b70a-7e0c964ebe99.png)
![image](https://user-images.githubusercontent.com/62998447/166637502-a560701a-703c-4699-9b56-17c55ce5a06f.png)

2022-05-04 07:27 UTC, alanneves requested changes
Could you please show a gif in the vertical/horizontal? We can't see animations in images yet.

2022-05-04 07:40 UTC, mickaelnn commented
> Could you please show a gif in the vertical/horizontal? We can't see animations in images yet.

Forgot the gif, sry

2022-05-04 08:50 UTC, caroltrindade approved these changes
LGTM
PS. I think this animation is very slow, but if it was approved by Bruna it's ok

2022-05-04 11:24 UTC, th3rius approved these changes
os cara trabalhando em primeiro turno

2022-05-04 11:24 UTC, th3rius commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +        const textWidth = text.length * 8;
Só uma nota: os caracteres nem sempre vão ter a mesma largura — talvez faça mais faz sentido usar um limite de caracteres fixo mesmo (ao invés de multiplicar por 8)

2022-05-04 13:22 UTC, alanneves requested changes

2022-05-04 13:22 UTC, alanneves commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +    textAbbreviated(text) {
to work with `...` you should use it:

`.text-overflow-elipsis {
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
}`

2022-05-04 14:40 UTC, alanneves approved these changes
LGTM

2022-05-04 14:42 UTC, merged

2022-05-05 18:44 UTC, planivic1 reviewed
LGTM