Feature/add new prop in date input
Adapcon/vue-polar-bear pull request #194
Opened 2022-07-08 19:03 UTC by planivic1

### Description
in this pr, I add a new prop in date input

2022-07-08 19:05 UTC, EvertonLMsilva submitted a review, later dismissed
LGTM

2022-07-09 13:54 UTC, alanneves commented
Can u put here an example with placeholder?

2022-07-09 14:58 UTC, ixpd requested changes

2022-07-09 14:58 UTC, ixpd commented on src/components/Inputs/DateInput/DateInput.vue
> +      :v-model="state.typeInput !== 'date' ? placeholder : inputDate"
esta validação/placeholder nao poderia ser adicionado no get da computed?

2022-07-11 18:15 UTC, EvertonLMsilva submitted a review, later dismissed
LGTM

2022-07-12 12:43 UTC, alanneves approved these changes
LOOKS GOOD TO ME

2022-07-12 12:47 UTC, victorstassun requested changes

2022-07-12 12:47 UTC, victorstassun commented on package.json
> +  "version": "0.10.7",
Update this version to 0.10.8 if it´s possible, we are already in the 0.10.7

2022-07-12 12:47 UTC, ixpd submitted a review, later dismissed
LGTM

2022-07-12 12:53 UTC, alanneves approved these changes
LGTM

2022-07-12 12:53 UTC, victorstassun approved these changes
LGTM

2022-07-12 12:54 UTC, EvertonLMsilva approved these changes
LGTM

2022-07-12 12:58 UTC, ixpd approved these changes

2022-07-12 12:59 UTC, merged