feat: adding status badge to pbTable
Adapcon/vue-polar-bear pull request #233
Opened 2022-08-25 19:23 UTC by victorstassun

### Description

Adding status badge on pbTable component.

Updating vue-polar-bear to 0.10.27

### Screenshots

![image](https://user-images.githubusercontent.com/82161592/186750768-1e06ef28-37b9-4462-a1cc-783560e86ec9.png)

2022-08-26 13:04 UTC, caroltrindade requested changes

2022-08-26 13:04 UTC, caroltrindade commented on src/components/DataVisualization/Table/Table.stories.mdx
> +          { value: 'Em Andamento', type: 'inProgress' },
Acho que 'type' fica muito abstrato, será que não seria legal usar a mesma prop 'badges' e fazer um badgesColor ou badgesStyle?

2022-08-26 13:04 UTC, caroltrindade commented on src/components/DataVisualization/Table/TableRows.vue
> +            <div class="status-container" v-if="column.type">
Os status vão ser fixos? Será que não daria pra vir com a cor de fora?

2022-08-26 13:16 UTC, caroltrindade commented on src/components/DataVisualization/Table/Table.stories.mdx
> +          { value: 'Em Andamento', type: 'inProgress' },
badges: [{ value: 'Banana', size: '', textColor: 'primary', backgroudColor: 'primary-light' }]
ou
badges: [{ value: 'Banana', size: '', color: 'primary' }]

2022-08-29 12:57 UTC, caroltrindade requested changes

2022-08-29 12:57 UTC, caroltrindade commented on src/components/DataVisualization/Table/Table.stories.mdx
> +    badgeSize: { type: 'string', defaultValue: 'pb-sm' },
Pode remover a prop direto da tabela, e deixar só recebendo no array de badges

2022-08-29 12:57 UTC, caroltrindade commented on src/components/DataVisualization/Table/Table.stories.mdx
> +          { badges: [{ value: 'Finalizado', badgeColor: 'success-light', badgeFontColor: 'success', badgeSize: 'pb-md' }] },
acho interessante tirar o prefixo 'badge' das propriedades porque fica bem repetitivo, talvez deixar só 'size', 'backgroundColor' e 'fontColor'

2022-08-29 13:15 UTC, caroltrindade approved these changes
LGTM

2022-08-29 13:27 UTC, planivic1 approved these changes

2022-08-29 13:27 UTC, merged