feat: adding closeOnOptionSelect prop to pbDropdown
Adapcon/vue-polar-bear pull request #237
Opened 2022-09-01 13:58 UTC by victorstassun

### Description

In this PR, I added the closeOnOptionSelect, that improves the pbDropdown component. Now you can select the closeOnOptionSelect prop when you want to close the dropdown when selecting an option.

### Screenshots

https://user-images.githubusercontent.com/82161592/187931119-34c08df4-18ba-4444-9372-24208f8df9b1.mp4

2022-09-01 14:01 UTC, VictorTavaress reviewed
cara achei muito bruta a troca tenta usar um transition acho que ficaria legal

2022-09-01 14:06 UTC, aXhwZA requested changes

2022-09-01 14:06 UTC, aXhwZA commented on src/components/MenusAndToolbars/Dropdown/Dropdown.vue
> +        @click="closeDropDownOnClick"
```suggestion
        @click="closeDropDownOnClick()"
```

2022-09-01 16:15 UTC, VictorTavaress submitted a review, later dismissed
LGMT

2022-09-01 18:22 UTC, aXhwZA requested changes
recomendo dar uma olhada no teu eslint, ta meio estranho esse fonte ai...

2022-09-01 18:30 UTC, gabrielforster submitted a review, later dismissed
LGTM

2022-09-01 18:57 UTC, GabrielPedrotti submitted a review, later dismissed
LGTM

2022-09-01 23:45 UTC, aXhwZA commented on src/components/MenusAndToolbars/Dropdown/Dropdown.vue
> +          `${withBoxShadow ? 'dropdown-box-shaddow' : '' }`
```suggestion
          `${ withBoxShadow ? 'dropdown-box-shaddow' : '' }`
```

2022-09-01 23:45 UTC, aXhwZA approved these changes

2022-09-02 11:31 UTC, GabrielPedrotti approved these changes
LGTM

2022-09-02 11:51 UTC, merged