[feat] Creating new prop on PbTable, useInternalFilter
Adapcon/vue-polar-bear pull request #288
Opened 2023-02-28 19:46 UTC by gabrielforster

### Description
This new prop is for use the internal filter or not. 
When the prop value is false, the component will just emit the sort event.
When it is true or not passed, the component will do the internal filter.

2023-02-28 19:48 UTC, VictorTavaress approved these changes

2023-02-28 19:49 UTC, LuquinhasSG submitted a review, later dismissed
LGTM

2023-03-01 08:31 UTC, caroltrindade requested changes

2023-03-01 08:31 UTC, caroltrindade commented on src/components/DataVisualization/Table/Table.stories.mdx
> +    useInternalFilter: { type: 'boolean', defaultValue: true },
change to useInternalSort

2023-03-01 08:31 UTC, caroltrindade commented on src/components/DataVisualization/Table/Table.vue
> +      if (!this.useInternalFilter) return;
You should emit the event only if the prop is true, otherwise, you will always emit the event even if the component must use the internal sort.

2023-03-01 10:56 UTC, VictorTavaress submitted a review, later dismissed

2023-03-01 11:02 UTC, LuquinhasSG submitted a review, later dismissed
LGTM

2023-03-01 11:43 UTC, marcosalves-bitg approved these changes
LGTM

2023-03-01 11:51 UTC, caroltrindade approved these changes
LGTM

2023-03-01 11:51 UTC, caroltrindade commented on src/components/DataVisualization/Table/Table.vue
> +      console.log(this.useInternalSort);
```suggestion
```

2023-03-01 12:00 UTC, caroltrindade approved these changes
LGTM

2023-03-01 12:01 UTC, marcosalves-bitg approved these changes
LGTM

2023-03-01 12:01 UTC, merged