feat: creation of new tab
Adapcon/vue-polar-bear pull request #29
Opened 2022-01-31 20:22 UTC by planivic1

In this Pr I creating a new tab that can be edited

2022-02-01 19:38 UTC, ixpd approved these changes
LGTM

2022-02-02 16:40 UTC, marcosalves-bitg submitted a review, later dismissed
LGTM

2022-02-02 16:43 UTC, Viserion77 requested changes

2022-02-02 16:43 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +    dynamicTabs: { type: Object, default: () => ({}) },
para que é usado?

2022-02-02 16:43 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +              :style="{'backgroundColor': colorOpacity}"
colorOpacity? primary?

2022-02-02 16:43 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +        inputValue: 'Tab',
para que é usado?

2022-02-02 16:43 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +        return event.target.value = 'Tab';
esta validação deveria estar dentro do addtab

2022-02-02 16:43 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +    addInputValue(event, tab) {
```suggestion
    },

    deleteTab(tab) {
      this.$delete(this.updateTabs, tab);
    },

    addInputValue(event, tab) {
```

2022-02-02 16:44 UTC, Viserion77 approved these changes
vou aprovar o o @ixpd pediu

2022-02-02 16:53 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +              :style="{'backgroundColor': colorOpacity}"
ve tbm sobre a prop 'color'

2022-02-02 18:11 UTC, Viserion77 approved these changes
LGTM

2022-02-02 18:11 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +    },
```suggestion
    addTabs(value = 'Tab') {
      cosnt newTabName = value || 'new tab'
      const valueKey = newTabName.replace(/-./g, x => x[1].toUpperCase());

      this.$set(this.updateTabs, valueKey, newTabName);
      this.$nextTick(() => {
        this.$emit('update:selected-tab', valueKey);
      });
    },
```

2022-02-02 18:15 UTC, ixpd submitted a review, later dismissed
LGTM

2022-02-02 18:28 UTC, ixpd approved these changes
LGTM

2022-02-02 18:28 UTC, Viserion77 submitted a review, later dismissed
LGTM

2022-02-02 20:12 UTC, ixpd requested changes

2022-02-02 20:12 UTC, ixpd commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +      cosnt newTabName = value || 'new tab'
A declaração da variavel está errada.

2022-02-03 11:11 UTC, ixpd approved these changes
LGTM

2022-02-03 11:21 UTC, Viserion77 approved these changes
LGTM

2022-02-03 11:21 UTC, merged