feat: creation of data table component
Adapcon/vue-polar-bear pull request #33
Opened 2022-02-03 18:28 UTC by planivic1

in this pr I create new component

2022-02-03 18:50 UTC, ixpd requested changes

2022-02-03 18:50 UTC, ixpd commented on src/components/DataVisualization/DataTable/DataTable.stories.mdx
> +        showHeader
O boolean dessa prop está funcionando no Storybook?

2022-02-03 18:50 UTC, ixpd commented on src/components/DataVisualization/DataTable/DataTable.stories.mdx
> +        showSortIcon
O boolean dessa prop está funcionando no Storybook?

2022-02-03 18:50 UTC, ixpd commented on src/components/DataVisualization/DataTable/DataTable.vue
> +      default: () => {},
```suggestion
      default: () => ({}),
```

2022-02-03 18:50 UTC, ixpd commented on src/components/DataVisualization/DataTable/DataTable.vue
> +  ],
está sendo utilizado em algum lugar?

2022-02-03 18:50 UTC, ixpd commented on src/components/DataVisualization/DataTable/ListData.vue
> +      console.log(array);
Remover Log

2022-02-03 18:50 UTC, ixpd commented on src/components/DataVisualization/DataTable/ListData.vue
> +      }
Não teria alguma outra alternativa para utilizar no lugar do 'for in'?

2022-02-03 19:34 UTC, ixpd approved these changes
LGTM

2022-02-04 09:26 UTC, Viserion77 requested changes

2022-02-04 09:26 UTC, Viserion77 commented on src/components/DataVisualization/DataTable/ListData.vue
> +      v-if="entities == ''"
esta comparando se array é uma string vazia? (sempre usamos 3 igual para comparação)

2022-02-04 09:26 UTC, Viserion77 commented on src/components/DataVisualization/DataTable/ListData.vue
> +    </div>
Deveria ser um componente

2022-02-04 09:26 UTC, Viserion77 commented on src/components/DataVisualization/DataTable/DataTable.vue
> +    },
você não usa o 'loadedEntities'

2022-02-04 09:26 UTC, Viserion77 commented on src/components/DataVisualization/DataTable/DataTable.vue
> +    },
essas configurações pederiam ficar dentro de um parametro chamado de settings, ou não? @ixpd

2022-02-04 11:53 UTC, ixpd commented on src/components/DataVisualization/DataTable/DataTable.vue
> +    },
@Viserion77 vale a pena deixar as props dentro de settings?
tem alguma vantagem ao alterar desta maneira?
funcionaria de boas no storybook?

2022-02-04 12:04 UTC, Viserion77 commented on src/components/DataVisualization/DataTable/DataTable.vue
> +    },
vai ter mais parametros dentro do compoente, e no SB tem como configurar certinho.

No SB:
```
<componente
   :settings="{
     title,
     showHeader
   }"
>
```

teria que testar

2022-02-04 14:22 UTC, Viserion77 approved these changes
LGTM

2022-02-04 14:23 UTC, ixpd approved these changes
LGTM

2022-02-04 14:23 UTC, merged