Feature/added configuration to disable button hover
Adapcon/vue-polar-bear pull request #4
Opened 2021-11-10 18:18 UTC by caroltrindade

### Description

This PR adds a configuration to disable the button hover.

2021-11-11 11:40 UTC, mickaelnn approved these changes
LGTM

2021-11-12 15:08 UTC, mickaelnn submitted a review, later dismissed
LGTM

2021-11-12 16:35 UTC, ricardobaehr approved these changes
LGTM

2021-11-12 16:39 UTC, alanneves requested changes

2021-11-12 16:39 UTC, alanneves commented on src/components/Buttons/Button/Button.vue
> +        'pb-button-style-regular-no-hover': this.buttonStyle === 'regular' && !this.isHovered,
só pode passar a prop isHovered se o style é regular?

2021-11-12 16:39 UTC, alanneves commented on src/components/Buttons/Button/Button.vue
> +    isHovered: {
Não é melhor uma prop chamada disableHover com default false?

ai quando fosse usar só usaria: `disable-hover`

2021-11-12 16:40 UTC, caroltrindade commented on src/components/Buttons/Button/Button.vue
> +        'pb-button-style-regular-no-hover': this.buttonStyle === 'regular' && !this.isHovered,
Os outros estilos não tem hover, só o regular mesmo 😄

2021-11-12 16:41 UTC, caroltrindade commented on src/components/Buttons/Button/Button.vue
> +    isHovered: {
Posso mudar 😄

2021-11-12 17:00 UTC, caroltrindade commented on src/components/Buttons/Button/Button.vue
> +    isHovered: {
Corrigido.

2021-11-12 17:35 UTC, mickaelnn approved these changes
LGTM

2021-11-12 17:39 UTC, alanneves approved these changes

2021-11-12 17:59 UTC, Viserion77 approved these changes
LGTM

2021-11-12 18:07 UTC, merged