feat: add disabled in tabs
Adapcon/vue-polar-bear pull request #43
Opened 2022-02-15 19:32 UTC by planivic1

in this pr I add disabled function in tabs

2022-02-15 19:49 UTC, ixpd requested changes

2022-02-15 19:49 UTC, ixpd commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +            @click="tabSettings.disabled ? '': $emit('update:selected-tab', tab)"
```suggestion
            @click="tabSettings.disabled ? '' : $emit('update:selected-tab', tab)"
```

2022-02-15 19:49 UTC, ixpd commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +          @click="tabSettings.disabled ? '': $emit('update:selected-tab', tab)"
```suggestion
          @click="tabSettings.disabled ? '' : $emit('update:selected-tab', tab)"
```

2022-02-15 20:37 UTC, Viserion77 requested changes

2022-02-15 20:37 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/Tabs.vue
> +  .tab-content-disable {
```suggestion

  .tab-content-disable {
```

2022-02-15 20:37 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/tabs.stories.mdx
> +        data: {label: 'Dados', icon: 'fas fa-check', color: 'success', disabled: true},
```suggestion
        prices: 'Preços',
        photos: {label: 'Fotos', icon: 'fas fa-check'},
        data: {label: 'Dados', color: 'success'},
        cup: {label: 'Copa', disabled: true},
        homer: {label: 'Inicio', icon: 'fas fa-home', color: 'danger', disabled: true},```

2022-02-15 20:38 UTC, Viserion77 commented on src/components/Miscellaneous/Tabs/tabs.stories.mdx
> +        data: {label: 'Dados', icon: 'fas fa-check', color: 'success', disabled: true},
Feito desta forma para mostrar que atende todos os cenários

2022-02-16 11:43 UTC, ixpd approved these changes
LGTM

2022-02-16 12:46 UTC, Viserion77 approved these changes
LGTM

2022-02-16 16:31 UTC, merged