[FEATURE] Create new props LinearBar
Adapcon/vue-polar-bear pull request #434
Opened 2024-05-29 17:27 UTC by viniieng

### Description

Create new props Linear Bar

[BSWA-1911](https://adapcon.atlassian.net/jira/software/c/projects/BSWA/boards/52?assignee=712020%3A48dece61-7842-486e-8ecb-88d26bc648c6&selectedIssue=BSWA-1911)

2024-05-31 16:22 UTC, brunaboeger requested changes

2024-05-31 16:22 UTC, brunaboeger commented on package-lock.json
altere a versão do package-lock.json e package.json para "version": "4.3.12".

2024-05-31 16:52 UTC, gabrielforster requested changes

2024-05-31 16:52 UTC, gabrielforster commented on .nvmrc
isso aq nao deveria estar aq

2024-05-31 17:17 UTC, gabrielforster requested changes

2024-05-31 17:17 UTC, gabrielforster commented on src/components/DataVisualization/LinearBar/LinearBar.stories.mdx
> +      positionRight: {
position right?

2024-06-03 12:13 UTC, VictorTavaress submitted a review, later dismissed
LGTM

2024-06-03 12:21 UTC, CauaKath requested changes

2024-06-03 12:21 UTC, CauaKath commented on src/components/DataVisualization/LinearBar/LinearBar.vue
> +      :style="`width: ${barWidth}%; margin-bottom: 0;`"
wouldn't it be better if u pass a second paramenter called width type to allow the consumer to choose the width type between pixels (px), percent (%) or viewport width (vw)?

2024-06-03 12:24 UTC, brunaboeger commented on src/components/DataVisualization/LinearBar/LinearBar.stories.mdx
> +        :horizontal-value=" horizontalValue"
```suggestion
        :horizontal-value="horizontalValue"
```

2024-06-03 13:58 UTC, CauaKath approved these changes
LGTM

2024-06-03 13:59 UTC, VictorTavaress approved these changes
LGTM

2024-06-03 14:13 UTC, brunaboeger approved these changes
LGTM

2024-06-03 14:20 UTC, CauaKath approved these changes
LGTM

2024-06-03 16:49 UTC, gabrielforster approved these changes
LGTM

2024-06-03 16:50 UTC, merged