feat: validates mobile
Adapcon/vue-polar-bear pull request #59
Opened 2022-02-24 19:27 UTC by marcofeliponi

Validates mobile device for the use of side menu.

https://amctextil.atlassian.net/jira/software/c/projects/CO/boards/1?modal=detail&selectedIssue=CO-610&assignee=61f9614e1c9bb000727c168c

2022-02-24 19:37 UTC, Viserion77 requested changes

2022-02-24 19:37 UTC, Viserion77 commented on package.json
> +    "storybook": "^6.4.19",
```suggestion
```

2022-02-25 11:56 UTC, planivic1 approved these changes
LGTM

2022-02-25 13:19 UTC, Viserion77 approved these changes
LGTM

2022-02-25 13:37 UTC, merged