fix: scroll base size and border radius
Adapcon/vue-polar-bear pull request #8
Opened 2021-11-24 16:33 UTC by planivic1

in this pr I fix the size of scroll and add border radius

2021-11-24 16:39 UTC, Viserion77 approved these changes
LGTM

2021-11-24 17:21 UTC, alanneves requested changes
Você está alterando o tamanho de todos os scrolls? Se for isso, conforme mencionado em nosso pair programming no periodo matutino nós não podemos fazer isso pois isso pode quebrar alguns de nossos layouts.

Foi conversado com alguém sobre isso?

2021-11-24 17:25 UTC, Viserion77 commented
Antes de alterar foi alinhado com a Bruna sobre isto, segundo ela não existe nenhum impacto em layout do mobile, já que é uma diferença de 6px.

Se realmente existir um possível erro, teria como apresentar onde ele esta? já vemos e resolvemos, pois o scroll deveria ser de um tamanho único em todo portal...

2021-11-24 17:27 UTC, alanneves approved these changes

2021-11-24 17:29 UTC, mickaelnn submitted a review, later dismissed
LGTM

2021-11-24 17:34 UTC, alanneves reviewed
Lembrar de verificar que há um arquivo igual no PRO, verificar o que fazer

2021-11-25 12:22 UTC, Viserion77 commented
@alanneves 
Pr ajustando no portal [-> 5862](https://github.com/Adapcon/simplificamais-app/pull/5862)

2021-11-25 12:27 UTC, mickaelnn approved these changes
lgtm

2021-11-25 12:31 UTC, caroltrindade requested changes
LGTM

2021-11-25 12:31 UTC, caroltrindade commented on src/components/index.scss
> +.pb-scroll-secondary-large {
Em vez de criar as classes de large como novas classes, poderia seguir a mesma ideia que temos no estilo da tag p, onde apenas colocamos qual vai ser o sufixo e assim fica tudo relacionado em um local só....o que acham?
![image](https://user-images.githubusercontent.com/32417804/143442155-bcba616a-779f-4603-a50e-113af46dfb13.png)

2021-11-25 13:08 UTC, Viserion77 commented on src/components/index.scss
> +.pb-scroll-secondary-large {
Pode ser, desconhecia essa pratica

2021-11-25 14:13 UTC, Viserion77 commented
Atualização da versão no protal neste pr: [5869](https://github.com/Adapcon/simplificamais-app/pull/5869)

2021-11-25 14:16 UTC, caroltrindade approved these changes
LGTM

2021-11-25 14:37 UTC, alanneves approved these changes
LGTM

2021-11-25 14:42 UTC, marcosalves-bitg approved these changes
LGTM

2021-11-25 14:42 UTC, merged