Fix/data table list row
Adapcon/vue-polar-bear pull request #99
Opened 2022-03-21 14:44 UTC by Viserion77

This pr add a sort to columns in PB data table and center utils off entity schema

2022-03-21 14:56 UTC, ixpd requested changes

2022-03-21 14:56 UTC, ixpd commented on src/components/DataVisualization/DataTable/ListRow.vue
> +    tableSchema: { type: Array, default: () => ([]) },
```suggestion
    tableSchema: { type: Array, default: () => [] },
```

2022-03-25 12:43 UTC, ixpd approved these changes
LGTM

2022-03-25 13:16 UTC, marcofeliponi approved these changes
LGTM

2022-03-25 13:16 UTC, merged